### PR TITLE
Ux improvements

### LINKED ISSUE #61: Improve User Experience: Different modes
As a user I want to be able to configure the FilterGraph fast without having to re-click through the manipulation menu of visjs in order to add edges and nodes.
The following modes should be implemented:
- Select Mode: Selecting Nodes and adjust their parameters
- Edit Mode: Add nodes and connections between nodes
- Delete Mode: Delete nodes and connections between nodes
A short help text should tell me what I can do with the nodes and edges if I hover over them with the mouse.

### PR DESCRIPTION
**Pull request by segfault16**
This resolves #61.

### CODE REVIEW

**Comment by segfault16** [comment]
Fixed issue with upload configuration. 

Create mode behaves the same as if you had 'add edge' enabled in visjs manipulation mode. I believe this is an issue with visjs. 

Created #66 for floating info box. Not a priority right now.

**Comment by fruechtegott** [comment]
Changes look good. But trying to get edges to connect is a real pain. Do we need a separate edges mode?

**Comment by segfault16** [comment]
Initially connecting edges was possible by dragging from effect to effect and selecting input and output channels in a separate popup. This was not really intuitive for me. Any suggestions?

**Comment by fruechtegott** [comment]
~~Don't get me wrong. I like the way it works now. The problem is that it does not work right now. Try loading the default project, delete the edge and try reconnecting it.~~
The problem only exists in safari. Chromium is all good.

**Comment by segfault16** [comment]
@fruechtegott Please review.

**Pull request merged**
