### PR TITLE
Basic Panels

### LINKED ISSUE #76: Support Panel Effects
After #73 we can think of how to configure LED panels as LED Output Effects and propagate the panel size through the effect chain while keeping all effects compatible.

### LINKED ISSUE #78: Audio-Reactive Falling Stars
It would be cool if the Falling Stars effect would be audio-reactive, so that stars emerge in sync with the audio input. I think some randomness should still be configurable, making the effect audio-reactive as well as generative. If the configuration is too complex we can use two different effects.

### LINKED ISSUE #86: FadeCandy Connection for larger number of pixels broken
When sending more than approx. 350 pixels to FadeCandy server the connection seems to be broken.
The client sends messages of the always the same length, but the server receives messages with size 0 or expects very large messages, which results in lag, wrong messages being decoded etc

### PR DESCRIPTION
**Pull request by segfault16**
This PR adds initial support for LED panels.
- [x] Support panels while being compatible to LED strip only setups. Resolves #76.
- [x] Adds some pattern generation implementations (Square, Diamond, Ruby, Batman, Labyrinth) of #82.
- [x] Add audio-reactive Falling Stars. Resolves #78.
- [x] Improve OPC message handling. Resolves #86.
- [x] Adjust storage of projects (now supports sub-folders, enabling configuration to be in git)

### CODE REVIEW

**Comment by fruechtegott** [comment]
The panelize effects create an error when trying to connect. Please add a working effect configuration.

**Comment by segfault16** [comment]
> The panelize effects create an error when trying to connect. Please add a working effect configuration.

I've added a config file.

**Comment by segfault16** [comment]
Was an issue with server config. PR is done I think.

**Comment by segfault16** [comment]
Tested with local setup and two Pi's. Force merging this now. @fruechtegott

**Pull request merged**
